version: 1.0.0

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: true
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.ddl-auto: validate
      hibernate.format_sql: true
  datasource:
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Guiga123
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    default-schema: biblioteca
    user: postgres
    password: Guiga123